---

- hosts: web_servers
  become: true
  tasks:
  
  - name: install apache and php packages
    tags: apache,apache2,ubuntu
    package:
      name: 
        - "{{ apache_package }}"
        - "{{ php_package }}"
      state: latest
      update_cache: yes
  - name: copy default html file for site
    tags: apache,apache2,ubuntu
    copy:
      src: default_site.html
      dest: /var/www/html/index.html
      owner: root
      group: root
      mode: 0644

- hosts: db_servers
  become: true
  tasks:
  
  - name: install mariadb package
    tags: db,mariadb,ubuntu
    package:
      name: 
        - "{{ mariadb_package }}"
      state: latest
      update_cache: yes

  - name: uninstall apache & php
    package:
      name:
        - "{{ apache_package }}"
        - "{{ php_package }}"

- hosts: file_servers
  become: true
  tasks:
  
  - name: install samba package
    tags: samba
    package:
      name: 
        - "{{ samba_package }}"
      state: latest
      update_cache: yes


