---

- hosts: all
  become: true
  pre_tasks:

    - name: Update repository index
      tags: always
      package:
        update_cache: yes
      changed_when: false


- hosts: all
  become: true
  roles:
    - base


- hosts: all
  become: true
  roles:
    - workstations

- hosts: all
  become: true
  roles:
    - web_servers

- hosts: all
  become: true
  roles:
    - db_servers


- hosts: all
  become: true
  roles:
    - file_servers


