- name: install apache and php packages                                                                              11:00:36 [76/130]
  tags: apache,apache2,ubuntu                                                                                                         
  package:                                                                                                                            
    name:                                                                                                                             
        - apache2
        - libapache2-mod-php
    state: latest                                                                                                                     

- name: copy default html file for site                                                                                               
  tags: apache,apache2,ubuntu                                                                                                         
  copy:                                                                                                                               
    src: default_site.html                                                                                                            
    dest: /var/www/html/index.html                                                                                                    
    owner: root                                                                                                                       
    group: root
    mode: 0644

- name: restart apache2 ubuntu
  tags: apache,apache2,ubuntu
  service:
    name: apache2
    state: restarted
    enabled: true

