- name: install apache and php packages                                                                              11:00:36 [76/130]
  tags: apache,apache2,ubuntu                                                                                                         
  package:                                                                                                                            
    name:                                                                                                                             
        - "{{ apache_package_name }}"
        - "{{ php_package_name }}"
    state: latest                                                                                                                     

- name: copy default html file for site                                                                                               
  tags: apache,apache2,ubuntu                                                                                                         
  copy:                                                                                                                               
    src: default_site.html                                                                                                            
    dest: /var/www/html/index.html                                                                                                    
    owner: root                                                                                                                       
    group: root
    mode: 0644
  notify: restart_apache

    #- name: restart apache2 ubuntu
    #tags: apache,apache2,ubuntu
    #service:
    #name: "{{ apache_service }}"
    #state: restarted
    #enabled: true

